const data = [
  { title: "ncert chemistry 1.pdf  NCERT Class 11", url: "/ncert.html" },
  { title: "ncert chemistry 2.pdf  NCERT Class 11", url: "/ncert.html" },
  { title: "ncert physics1.pdf  NCERT Class 11", url: "/ncert.html" },
  { title: "ncert physics2.pdf  NCERT Class 11", url: "/ncert.html" },
  { title: "NCERT_CLASS_11_BIOLOGY.pdf  NCERT Class 11", url: "/ncert.html" },
  { title: "NCERT_CLASS_11_MATHEMATICS_ENGLISH.pdf  NCERT Class 11", url: "/ncert.html" },
  { title: "Algebra.pdf  Arihant", url: "/books.html" },
  { title: "Coordinate Geometry.pdf  Arihant", url: "/books.html" },
  { title: "Differential Calculus.pdf  Arihant", url: "/books.html" },
  { title: "Integral Calculus.pdf  Arihant", url: "/books.html" },
  { title: "Play with Graphs.pdf  Arihant", url: "/books.html" },
  { title: "Trigonometry.pdf  Arihant", url: "/books.html" },
  { title: "Vectors and 3D Geometry.pdf  Arihant", url: "/books.html" },
  { title: "Arjuna chemistry module-1.pdf  PW-Physics Wallah", url: "/books.html" },
  { title: "Arjuna chemistry module-2.pdf  PW-Physics Wallah", url: "/books.html" },
  { title: "Arjuna chemistry module-3.pdf  PW-Physics Wallah", url: "/books.html" },
  { title: "Arjuna chemistry module-4.pdf  PW-Physics Wallah", url: "/books.html" },
  { title: "Arjuna mathematics module-1.pdf  PW-Physics Wallah", url: "/books.html" },
  { title: "Arjuna mathematics module-2.pdf  PW-Physics Wallah", url: "/books.html" },
  { title: "Arjuna mathematics module-3.pdf  PW-Physics Wallah", url: "/books.html" },
  { title: "Arjuna mathematics module-4.pdf  PW-Physics Wallah", url: "/books.html" },
  { title: "Arjuna physics module-1.pdf  PW-Physics Wallah", url: "/books.html" },
  { title: "Arjuna physics module-2.pdf  PW-Physics Wallah", url: "/books.html" },
  { title: "Arjuna physics module-3.pdf  PW-Physics Wallah", url: "/books.html" },
  { title: "Arjuna physics module-4 iityatra.pdf  PW-Physics Wallah", url: "/books.html" },
  { title: "PW Chemistry 2024 Handbook.pdf  PW-Physics Wallah", url: "/notes.html" },
  { title: "PW Mathematics 2024 Handbook.pdf  PW-Physics Wallah", url: "/notes.html" },
  { title: "PW Physics 2024 Handbook.pdf  PW-Physics Wallah", url: "/notes.html" },
  
  { title: "JEE Advanced Question Paper 2007 Paper 1.pdf", url: "/question-bank.html" },
  { title: "JEE Advanced Question Paper 2007 Paper 2.pdf", url: "/question-bank.html" },
  { title: "JEE Advanced Question Paper 2008 Paper 1.pdf", url: "/question-bank.html" },
  { title: "JEE Advanced Question Paper 2008 Paper 2.pdf", url: "/question-bank.html" },
  { title: "JEE Advanced Question Paper 2009 Paper 1.pdf", url: "/question-bank.html" },
  { title: "JEE Advanced Question Paper 2009 Paper 2.pdf", url: "/question-bank.html" },
  { title: "JEE Advanced Question Paper 2010 Paper 1.pdf", url: "/question-bank.html" },
  { title: "JEE Advanced Question Paper 2010 Paper 2.pdf", url: "/question-bank.html" },
  { title: "JEE Advanced Question Paper 2011 Paper 1.pdf", url: "/question-bank.html" },
  { title: "JEE Advanced Question Paper 2011 Paper 2.pdf", url: "/question-bank.html" },
  { title: "JEE Advanced Question Paper 2012 Paper 1.pdf", url: "/question-bank.html" },
  { title: "JEE Advanced Question Paper 2013 Paper 1.pdf", url: "/question-bank.html" },
  { title: "JEE Advanced Question Paper 2014 Paper 2.pdf", url: "/question-bank.html" },
  { title: "JEE Advanced Question Paper 2015 Paper 1.pdf", url: "/question-bank.html" },
  { title: "JEE Advanced Question Paper 2016 Paper 2.pdf", url: "/question-bank.html" },
  { title: "JEE Advanced Question Paper 2017 Paper 2.pdf", url: "/question-bank.html" },
  { title: "JEE Advanced Question Paper 2018 Paper 2.pdf", url: "/question-bank.html" },
  { title: "JEE Advanced Question Paper 2019 Paper 2.pdf", url: "/question-bank.html" },
  { title: "JEE Advanced Question Paper 2020 Paper 1.pdf", url: "/question-bank.html" },
  { title: "disha pyq chemistry.pdf", url: "/question-bank.html" },
  { title: "disha pyq mathematics.pdf", url: "/question-bank.html" },
  { title: "disha pyq Physics.pdf", url: "/question-bank.html" }
];


